package base;
dialect  "mvel"
import com.drools.fact.Config
import com.drools.fact.Person

rule "base2"
@ruleCode("testRuleCode")
    when
        $p : Person($age:age > 20)
//        $c : Config(ruleCode == "testRuleCode",$current:currentRuns)
    then
        modify($p){
            setAge($age - 1)
        }
//        modify($c){
//            setCurrentRuns($current + 1)
//        }
        System.out.println("p:" + $p);
end

rule "base-test1"
lock-on-active true
    when
        $p : Person()
    then
    System.out.println("base-test3");
end

rule "base-test2"
lock-on-active true
    when
        $p : Person()
    then
    System.out.println("base-test2");
end

rule "base-test3"
lock-on-active true
    when
        $p : Person()
    then
    System.out.println("base-test3");
end
