package rools;
import java.util.Date
import com.drools.fact.Person
import com.drools.fact.Address
import java.util.List
dialect  "mvel"

declare Child
    @role(event)
    name:String
    age:Integer
    birthday:Date
end

query "people over the age of 30"
    person : Person( age > 30 )
end

rule "Assign people in North Carolina (NC) to sales region 1"
agenda-group "test-from"
lock-on-active true
when
    $p : Person($addresses:addresses)

//    from accumulate(Person(username="AAA",$age:age),
//                init(int total = 0;),
//                action(total += $age;),
//                reverse(total -= $age;),
//                result(total))
    exists (Address( name == "NC") from $addresses)
then
    System.out.println($p);
    modify ($p) {setAge(16)} // Modify assessment in a modify block
end


rule "Apply a discount to people in the city of Raleigh"
agenda-group "test-from"
lock-on-active true
when
//    $p : Person()
//    $addresses : List() from $p.addresses
    $p : Person($addresses:addresses)
    exists (Address( name == "Raleigh") from $addresses)
then
    System.out.println($p);
    modify ($p) {setMarried(Boolean.TRUE)} // Modify assessment in a modify block
end

rule "a condition with more one then"
agenda-group "test-then"
lock-on-active true
when
    $p : Person($name : username)
    if ($name == "koudai") do[koudaiHello]
    //飘红代表当前idea不支持，并不是错误的写法
    else if ($name == "goudan") break[goudanGun]
then
    System.out.println($p);
then[koudaiHello]
    System.out.println("hello,"+$name);
then[goudanGun]
    System.out.println("gun,"+$name);
end

//rule "test"
//agenda-group "test-query"
//when
//    "people over the age of x"(12)
//then
//    System.out.println($p);
//end

//rule "rule-fact-type"
//when
//    $c:Child(age > 10);
//then
//    System.out.println("rule-fact-type触发:"+$c);
//end

rule "rule-CEP"
when
    Number(doubleValue > 5) from accumulate(
                Child(age > 10) over window:time(10m),
                count(1)
            )

then
    System.out.println("rule-CEP触发");
end
