package rools;
import com.drools.fact.Person
import com.drools.fact.AdultBusPass
import com.drools.fact.ChildBusPass
dialect  "mvel"

rule "fact-handler-test"
lock-on-active
agenda-group "fact-handler-group"
    when
        $p:Person(age >= 20,birthday > "2019-02-28 11:12:13",$boolean : username!.empty)
        $p1:Person(age >= 33)
    then
        modify($p){setUsername("二狗子")}
        System.out.println($p.getUsername()+$boolean);
end


