package cep;
import com.drools.fact.Person
dialect  "mvel"
//declare Person
//    @Role(event)
//    @expires(2s)
//end

//length(1),基于长度
//time(2s),基于时间

rule "cep-time"
    when
        accumulate($p : Person(age > 3,$username:username) over window : time(2s);
            $list:collectList($username),
            $count:count(1)
        )

    then
        System.out.println("list:"+$list);
        System.out.println("$count:"+$count);
end

rule "cep-length"
    when
        accumulate($p : Person(age > 3,$username:username) over window : length(2);
            $list:collectList($username),
            $count:count(1)
        )

    then
        System.out.println("list:"+$list);
        System.out.println("$count:"+$count);
end
