package rools;
import com.drools.fact.Person
dialect  "mvel"

rule "stateless"
    when
        $p:Person(age >= 20)
    then
        System.out.println($p.getUsername());
end

//IMMEDIATE表示传播立即执行。
//EAGER意味着传播是在计划的评估之前懒惰地进行但是急切地评估。
//LAZY意味着传播完全是懒惰的，这是(默认)的PHREAK行为
query Q (Integer i)
    String( this == i.toString() )
end
rule R @Propagation(IMMEDIATE) when
    $i : Integer()
    ?Q( $i; )
then
    System.out.println( $i + ":" + $i.getClass());
end