package rools;
import com.drools.fact.order.Order
import com.drools.fact.order.OrderEntry
import com.drools.fact.order.DiscountValue
import java.util.UUID
import java.util.Arrays
import java.math.BigDecimal
dialect  "mvel"

function String hello(String name){
    return "hello"+name+"!";
}

rule "promotion-group-test"
agenda-group "promotion-group"
    when
        $order:Order(orderEntries.size() > 1 && totalPrice > 1900)
    then
        DiscountValue discountValue = new DiscountValue(UUID.randomUUID().toString(),BigDecimal.valueOf(100));
        modify($order){setDiscountValues(Arrays.asList(discountValue))}
end

rule "promotion-group-test1"
agenda-group "promotion-group"
    when
        $order:Order()
        accumulate(OrderEntry(order == $order,$price:price);
                   $min:min($price))
    then
        System.out.println("============" + $min);
end

